export class WellnessConstants {
  public static get Prod_url(): string {
    return "https://www.meschinowellness.com/";
  }
  public static get Demo_url(): string {
    return "http://demo-meschinowellness.azurewebsites.net/";
  }
  public static get Staging_url(): string {
    return "http://stage-meschinowellness.azurewebsites.net/";
  }

  public static get App_Url(): string {
    return "https://www.meschinowellness.com/";
  }

  public static get weightData(): any {
    return [
      { description: "140" },
      { description: "141" },
      { description: "142" },
      { description: "143" },
      { description: "144" },
      { description: "145" },
      { description: "146" },
      { description: "147" },
      { description: "148" },
      { description: "149" },
      { description: "150" },
      { description: "151" },
      { description: "152" },
      { description: "153" },
      { description: "154" },
      { description: "155" },
      { description: "156" },
      { description: "157" },
      { description: "158" },
      { description: "159" }
    ];
  }

  public static get waistData(): any {
    return [
      { description: "28" },
      { description: "30" },
      { description: "32" },
      { description: "34" },
      { description: "36" },
      { description: "38" },
      { description: "40" },
      { description: "42" },
      { description: "44" },
      { description: "46" },
      { description: "48" },
      { description: "50" },
      { description: "52" },
      { description: "54" },
      { description: "56" },
      { description: "58" },
      { description: "60" },
      { description: "62" },
      { description: "64" },
      { description: "66" },
      { description: "68" },
      { description: "70" }
    ];
  }

  public static get parentColumns(): any {
    return [
      {
        name: "unit",
        options: [
          { text: "Feet/ Inches", value: "feet" },
          { text: "CMS", value: "cm" }
        ]
      },
      {
        name: "Value",
        parentCol: "unit",
        options: [
          { text: "  1", value: "1", parentVal: "feet" },
          { text: "  2", value: "2", parentVal: "feet" },
          { text: "  3", value: "3", parentVal: "feet" },
          { text: "  4", value: "4", parentVal: "feet" },
          { text: "  5", value: "5", parentVal: "feet" },
          { text: "  6", value: "6", parentVal: "feet" },
          { text: "  7", value: "7", parentVal: "feet" },
          //{ text: "  8", value: "8", parentVal: "feet" },

          { text: " 30", value: "30", parentVal: "cm" },
          { text: " 31", value: "31", parentVal: "cm" },
          { text: " 32", value: "32", parentVal: "cm" },
          { text: " 33", value: "33", parentVal: "cm" },
          { text: " 34", value: "34", parentVal: "cm" },
          { text: " 35", value: "35", parentVal: "cm" },
          { text: " 36", value: "36", parentVal: "cm" },
          { text: " 37", value: "37", parentVal: "cm" },
          { text: " 38", value: "38", parentVal: "cm" },
          { text: " 39", value: "39", parentVal: "cm" },
          { text: " 40", value: "40", parentVal: "cm" },

          { text: " 41", value: "41", parentVal: "cm" },
          { text: " 42", value: "42", parentVal: "cm" },
          { text: " 43", value: "43", parentVal: "cm" },
          { text: " 44", value: "44", parentVal: "cm" },
          { text: " 45", value: "45", parentVal: "cm" },
          { text: " 46", value: "46", parentVal: "cm" },
          { text: " 47", value: "47", parentVal: "cm" },
          { text: " 48", value: "48", parentVal: "cm" },
          { text: " 49", value: "49", parentVal: "cm" },
          { text: " 50", value: "50", parentVal: "cm" },

          { text: " 51", value: "51", parentVal: "cm" },
          { text: " 52", value: "52", parentVal: "cm" },
          { text: " 53", value: "53", parentVal: "cm" },
          { text: " 54", value: "54", parentVal: "cm" },
          { text: " 55", value: "55", parentVal: "cm" },
          { text: " 56", value: "56", parentVal: "cm" },
          { text: " 57", value: "57", parentVal: "cm" },
          { text: " 58", value: "58", parentVal: "cm" },
          { text: " 59", value: "59", parentVal: "cm" },
          { text: " 60", value: "60", parentVal: "cm" },

          { text: " 61", value: "61", parentVal: "cm" },
          { text: " 62", value: "62", parentVal: "cm" },
          { text: " 63", value: "63", parentVal: "cm" },
          { text: " 64", value: "64", parentVal: "cm" },
          { text: " 65", value: "65", parentVal: "cm" },
          { text: " 66", value: "66", parentVal: "cm" },
          { text: " 67", value: "67", parentVal: "cm" },
          { text: " 68", value: "68", parentVal: "cm" },
          { text: " 69", value: "69", parentVal: "cm" },
          { text: " 70", value: "70", parentVal: "cm" },

          { text: " 71", value: "71", parentVal: "cm" },
          { text: " 72", value: "72", parentVal: "cm" },
          { text: " 73", value: "73", parentVal: "cm" },
          { text: " 74", value: "74", parentVal: "cm" },
          { text: " 75", value: "75", parentVal: "cm" },
          { text: " 76", value: "76", parentVal: "cm" },
          { text: " 77", value: "77", parentVal: "cm" },
          { text: " 78", value: "78", parentVal: "cm" },
          { text: " 79", value: "79", parentVal: "cm" },
          { text: " 80", value: "80", parentVal: "cm" },

          { text: " 81", value: "81", parentVal: "cm" },
          { text: " 82", value: "82", parentVal: "cm" },
          { text: " 83", value: "83", parentVal: "cm" },
          { text: " 84", value: "84", parentVal: "cm" },
          { text: " 85", value: "85", parentVal: "cm" },
          { text: " 86", value: "86", parentVal: "cm" },
          { text: " 87", value: "87", parentVal: "cm" },
          { text: " 88", value: "88", parentVal: "cm" },
          { text: " 89", value: "89", parentVal: "cm" },
          { text: " 90", value: "90", parentVal: "cm" },

          { text: " 91", value: "91", parentVal: "cm" },
          { text: " 92", value: "92", parentVal: "cm" },
          { text: " 93", value: "93", parentVal: "cm" },
          { text: " 94", value: "94", parentVal: "cm" },
          { text: " 95", value: "95", parentVal: "cm" },
          { text: " 96", value: "96", parentVal: "cm" },
          { text: " 97", value: "97", parentVal: "cm" },
          { text: " 98", value: "98", parentVal: "cm" },
          { text: " 99", value: "99", parentVal: "cm" },
          { text: " 100", value: "100", parentVal: "cm" },

          { text: " 101", value: "101", parentVal: "cm" },
          { text: " 102", value: "102", parentVal: "cm" },
          { text: " 103", value: "103", parentVal: "cm" },
          { text: " 104", value: "104", parentVal: "cm" },
          { text: " 105", value: "105", parentVal: "cm" },
          { text: " 106", value: "106", parentVal: "cm" },
          { text: " 107", value: "107", parentVal: "cm" },
          { text: " 108", value: "108", parentVal: "cm" },
          { text: " 109", value: "109", parentVal: "cm" },
          { text: " 110", value: "110", parentVal: "cm" },

          { text: " 111", value: "111", parentVal: "cm" },
          { text: " 112", value: "112", parentVal: "cm" },
          { text: " 113", value: "113", parentVal: "cm" },
          { text: " 114", value: "114", parentVal: "cm" },
          { text: " 115", value: "115", parentVal: "cm" },
          { text: " 116", value: "116", parentVal: "cm" },
          { text: " 117", value: "117", parentVal: "cm" },
          { text: " 118", value: "118", parentVal: "cm" },
          { text: " 119", value: "119", parentVal: "cm" },
          { text: " 120", value: "120", parentVal: "cm" },

          { text: " 121", value: "121", parentVal: "cm" },
          { text: " 122", value: "122", parentVal: "cm" },
          { text: " 123", value: "123", parentVal: "cm" },
          { text: " 124", value: "124", parentVal: "cm" },
          { text: " 125", value: "125", parentVal: "cm" },
          { text: " 126", value: "126", parentVal: "cm" },
          { text: " 127", value: "127", parentVal: "cm" },
          { text: " 128", value: "128", parentVal: "cm" },
          { text: " 129", value: "129", parentVal: "cm" },
          { text: " 130", value: "130", parentVal: "cm" },

          { text: " 131", value: "131", parentVal: "cm" },
          { text: " 132", value: "132", parentVal: "cm" },
          { text: " 133", value: "133", parentVal: "cm" },
          { text: " 134", value: "134", parentVal: "cm" },
          { text: " 135", value: "135", parentVal: "cm" },
          { text: " 136", value: "136", parentVal: "cm" },
          { text: " 137", value: "137", parentVal: "cm" },
          { text: " 138", value: "138", parentVal: "cm" },
          { text: " 139", value: "139", parentVal: "cm" },
          { text: " 140", value: "140", parentVal: "cm" },

          { text: " 141", value: "141", parentVal: "cm" },
          { text: " 142", value: "142", parentVal: "cm" },
          { text: " 143", value: "143", parentVal: "cm" },
          { text: " 144", value: "144", parentVal: "cm" },
          { text: " 145", value: "145", parentVal: "cm" },
          { text: " 146", value: "146", parentVal: "cm" },
          { text: " 147", value: "147", parentVal: "cm" },
          { text: " 148", value: "148", parentVal: "cm" },
          { text: " 149", value: "149", parentVal: "cm" },
          { text: " 150", value: "150", parentVal: "cm" },

          { text: " 151", value: "151", parentVal: "cm" },
          { text: " 152", value: "152", parentVal: "cm" },
          { text: " 153", value: "153", parentVal: "cm" },
          { text: " 154", value: "154", parentVal: "cm" },
          { text: " 155", value: "155", parentVal: "cm" },
          { text: " 156", value: "156", parentVal: "cm" },
          { text: " 157", value: "157", parentVal: "cm" },
          { text: " 158", value: "158", parentVal: "cm" },
          { text: " 159", value: "159", parentVal: "cm" },
          { text: " 160", value: "160", parentVal: "cm" },

          { text: " 161", value: "161", parentVal: "cm" },
          { text: " 162", value: "162", parentVal: "cm" },
          { text: " 163", value: "163", parentVal: "cm" },
          { text: " 164", value: "164", parentVal: "cm" },
          { text: " 165", value: "165", parentVal: "cm" },
          { text: " 166", value: "166", parentVal: "cm" },
          { text: " 167", value: "167", parentVal: "cm" },
          { text: " 168", value: "168", parentVal: "cm" },
          { text: " 169", value: "169", parentVal: "cm" },
          { text: " 170", value: "170", parentVal: "cm" },

          { text: " 171", value: "171", parentVal: "cm" },
          { text: " 172", value: "172", parentVal: "cm" },
          { text: " 173", value: "173", parentVal: "cm" },
          { text: " 174", value: "174", parentVal: "cm" },
          { text: " 175", value: "175", parentVal: "cm" },
          { text: " 176", value: "176", parentVal: "cm" },
          { text: " 177", value: "177", parentVal: "cm" },
          { text: " 178", value: "178", parentVal: "cm" },
          { text: " 179", value: "179", parentVal: "cm" },
          { text: " 180", value: "180", parentVal: "cm" },

          { text: " 181", value: "181", parentVal: "cm" },
          { text: " 182", value: "182", parentVal: "cm" },
          { text: " 183", value: "183", parentVal: "cm" },
          { text: " 184", value: "184", parentVal: "cm" },
          { text: " 185", value: "185", parentVal: "cm" },
          { text: " 186", value: "186", parentVal: "cm" },
          { text: " 187", value: "187", parentVal: "cm" },
          { text: " 188", value: "188", parentVal: "cm" },
          { text: " 189", value: "189", parentVal: "cm" },
          { text: " 190", value: "190", parentVal: "cm" },

          { text: " 191", value: "191", parentVal: "cm" },
          { text: " 192", value: "192", parentVal: "cm" },
          { text: " 193", value: "193", parentVal: "cm" },
          { text: " 194", value: "194", parentVal: "cm" },
          { text: " 195", value: "195", parentVal: "cm" },
          { text: " 196", value: "196", parentVal: "cm" },
          { text: " 197", value: "197", parentVal: "cm" },
          { text: " 198", value: "198", parentVal: "cm" },
          { text: " 199", value: "199", parentVal: "cm" },
          { text: " 200", value: "200", parentVal: "cm" },

          { text: " 201", value: "201", parentVal: "cm" },
          { text: " 202", value: "202", parentVal: "cm" },
          { text: " 203", value: "203", parentVal: "cm" },
          { text: " 204", value: "204", parentVal: "cm" },
          { text: " 205", value: "205", parentVal: "cm" },
          { text: " 206", value: "206", parentVal: "cm" },
          { text: " 207", value: "207", parentVal: "cm" },
          { text: " 208", value: "208", parentVal: "cm" },
          { text: " 209", value: "209", parentVal: "cm" },
          { text: " 210", value: "210", parentVal: "cm" },

          { text: " 211", value: "211", parentVal: "cm" },
          { text: " 212", value: "212", parentVal: "cm" },
          { text: " 213", value: "213", parentVal: "cm" },
          { text: " 214", value: "214", parentVal: "cm" },
          { text: " 215", value: "215", parentVal: "cm" },
          { text: " 216", value: "216", parentVal: "cm" },
          { text: " 217", value: "217", parentVal: "cm" },
          { text: " 218", value: "218", parentVal: "cm" },
          { text: " 219", value: "219", parentVal: "cm" },
          { text: " 220", value: "220", parentVal: "cm" },

          { text: " 221", value: "221", parentVal: "cm" },
          { text: " 222", value: "222", parentVal: "cm" },
          { text: " 223", value: "223", parentVal: "cm" },
          { text: " 224", value: "224", parentVal: "cm" },
          { text: " 225", value: "225", parentVal: "cm" },
          { text: " 226", value: "226", parentVal: "cm" },
          { text: " 227", value: "227", parentVal: "cm" },
          { text: " 228", value: "228", parentVal: "cm" },
          { text: " 229", value: "229", parentVal: "cm" },
          { text: " 230", value: "230", parentVal: "cm" },

          { text: " 231", value: "231", parentVal: "cm" },
          { text: " 232", value: "232", parentVal: "cm" },
          { text: " 233", value: "233", parentVal: "cm" },
          { text: " 234", value: "234", parentVal: "cm" },
          { text: " 235", value: "235", parentVal: "cm" },
          { text: " 236", value: "236", parentVal: "cm" },
          { text: " 237", value: "237", parentVal: "cm" },
          { text: " 238", value: "238", parentVal: "cm" },
          { text: " 239", value: "239", parentVal: "cm" },
          { text: " 240", value: "240", parentVal: "cm" },
          { text: " 241", value: "241", parentVal: "cm" },
          { text: " 242", value: "242", parentVal: "cm" },
          { text: " 243", value: "243", parentVal: "cm" }
        ]
      },
      {
        name: "inches",
        parentCol: "Value",
        options: [
          { text: "0", value: "0", parentVal: "1" },
          { text: "1", value: "1", parentVal: "1" },
          { text: "2", value: "2", parentVal: "1" },
          { text: "3", value: "3", parentVal: "1" },
          { text: "4", value: "4", parentVal: "1" },
          { text: "5", value: "5", parentVal: "1" },
          { text: "6", value: "6", parentVal: "1" },
          { text: "7", value: "7", parentVal: "1" },
          { text: "8", value: "8", parentVal: "1" },
          { text: "9", value: "9", parentVal: "1" },
          { text: "10", value: "10", parentVal: "1" },
          { text: "11", value: "11", parentVal: "1" },
          { text: "12", value: "12", parentVal: "1" },

          { text: "0", value: "0", parentVal: "2" },
          { text: "1", value: "1", parentVal: "2" },
          { text: "2", value: "2", parentVal: "2" },
          { text: "3", value: "3", parentVal: "2" },
          { text: "4", value: "4", parentVal: "2" },
          { text: "5", value: "5", parentVal: "2" },
          { text: "6", value: "6", parentVal: "2" },
          { text: "7", value: "7", parentVal: "2" },
          { text: "8", value: "8", parentVal: "2" },
          { text: "9", value: "9", parentVal: "2" },
          { text: "10", value: "10", parentVal: "2" },
          { text: "11", value: "11", parentVal: "2" },
          { text: "12", value: "12", parentVal: "2" },

          { text: "0", value: "0", parentVal: "3" },
          { text: "1", value: "1", parentVal: "3" },
          { text: "2", value: "2", parentVal: "3" },
          { text: "3", value: "3", parentVal: "3" },
          { text: "4", value: "4", parentVal: "3" },
          { text: "5", value: "5", parentVal: "3" },
          { text: "6", value: "6", parentVal: "3" },
          { text: "7", value: "7", parentVal: "3" },
          { text: "8", value: "8", parentVal: "3" },
          { text: "9", value: "9", parentVal: "3" },
          { text: "10", value: "10", parentVal: "3" },
          { text: "11", value: "11", parentVal: "3" },
          { text: "12", value: "12", parentVal: "3" },

          { text: "0", value: "0", parentVal: "4" },
          { text: "1", value: "1", parentVal: "4" },
          { text: "2", value: "2", parentVal: "4" },
          { text: "3", value: "3", parentVal: "4" },
          { text: "4", value: "4", parentVal: "4" },
          { text: "5", value: "5", parentVal: "4" },
          { text: "6", value: "6", parentVal: "4" },
          { text: "7", value: "7", parentVal: "4" },
          { text: "8", value: "8", parentVal: "4" },
          { text: "9", value: "9", parentVal: "4" },
          { text: "10", value: "10", parentVal: "4" },
          { text: "11", value: "11", parentVal: "4" },
          { text: "12", value: "12", parentVal: "4" },

          { text: "0", value: "0", parentVal: "5" },
          { text: "1", value: "1", parentVal: "5" },
          { text: "2", value: "2", parentVal: "5" },
          { text: "3", value: "3", parentVal: "5" },
          { text: "4", value: "4", parentVal: "5" },
          { text: "5", value: "5", parentVal: "5" },
          { text: "6", value: "6", parentVal: "5" },
          { text: "7", value: "7", parentVal: "5" },
          { text: "8", value: "8", parentVal: "5" },
          { text: "9", value: "9", parentVal: "5" },
          { text: "10", value: "10", parentVal: "5" },
          { text: "11", value: "11", parentVal: "5" },
          { text: "12", value: "12", parentVal: "5" },

          { text: "0", value: "0", parentVal: "6" },
          { text: "1", value: "1", parentVal: "6" },
          { text: "2", value: "2", parentVal: "6" },
          { text: "3", value: "3", parentVal: "6" },
          { text: "4", value: "4", parentVal: "6" },
          { text: "5", value: "5", parentVal: "6" },
          { text: "6", value: "6", parentVal: "6" },
          { text: "7", value: "7", parentVal: "6" },
          { text: "8", value: "8", parentVal: "6" },
          { text: "9", value: "9", parentVal: "6" },
          { text: "10", value: "10", parentVal: "6" },
          { text: "11", value: "11", parentVal: "6" },
          { text: "12", value: "12", parentVal: "6" },

          { text: "0", value: "0", parentVal: "7" },
          { text: "1", value: "1", parentVal: "7" },
          { text: "2", value: "2", parentVal: "7" },
          { text: "3", value: "3", parentVal: "7" },
          { text: "4", value: "4", parentVal: "7" },
          { text: "5", value: "5", parentVal: "7" },
          { text: "6", value: "6", parentVal: "7" },
          { text: "7", value: "7", parentVal: "7" },
          { text: "8", value: "8", parentVal: "7" },
          { text: "9", value: "9", parentVal: "7" },
          { text: "10", value: "10", parentVal: "7" },
          { text: "11", value: "11", parentVal: "7" },
          { text: "12", value: "12", parentVal: "7" }
          /*
            // { text: "0", value: "0", parentVal: "8" },
            // { text: "1", value: "1", parentVal: "8" },
            // { text: "2", value: "2", parentVal: "8" },
            // { text: "3", value: "3", parentVal: "8" },
            // { text: "4", value: "4", parentVal: "8" },
            // { text: "5", value: "5", parentVal: "8" },
            // { text: "6", value: "6", parentVal: "8" },
            // { text: "7", value: "7", parentVal: "8" },
            // { text: "8", value: "8", parentVal: "8" },
            // { text: "9", value: "9", parentVal: "8" },
            // { text: "10", value: "10", parentVal: "8" },
            // { text: "11", value: "11", parentVal: "8" }
            // // { text: " 12", value: "12", parentVal: "8" },
  
            { text: "0", value: "0", parentVal: "130" },
            { text: "0", value: "0", parentVal: "141" },
            { text: "0", value: "0", parentVal: "142" },
            { text: "0", value: "0", parentVal: "143" },
            { text: "0", value: "0", parentVal: "144" },
            { text: "0", value: "0", parentVal: "145" },
            { text: "0", value: "0", parentVal: "146" },
            { text: "0", value: "0", parentVal: "147" },
            { text: "0", value: "0", parentVal: "148" },
            { text: "0", value: "0", parentVal: "149" },
            { text: "0", value: "0", parentVal: "150" },
            { text: "0", value: "0", parentVal: "151" },
            { text: "0", value: "0", parentVal: "152" },
            { text: "0", value: "0", parentVal: "153" },
            { text: "0", value: "0", parentVal: "154" },
            { text: "0", value: "0", parentVal: "155" },
            { text: "0", value: "0", parentVal: "156" },
            { text: "0", value: "0", parentVal: "157" },
            { text: "0", value: "0", parentVal: "158" },
            { text: "0", value: "0", parentVal: "159" },
            { text: "0", value: "0", parentVal: "160" },
            { text: "0", value: "0", parentVal: "161" },
            { text: "0", value: "0", parentVal: "162" },
            { text: "0", value: "0", parentVal: "163" },
            { text: "0", value: "0", parentVal: "164" },
            { text: "0", value: "0", parentVal: "165" },
            { text: "0", value: "0", parentVal: "166" },
            { text: "0", value: "0", parentVal: "167" },
            { text: "0", value: "0", parentVal: "168" },
            { text: "0", value: "0", parentVal: "169" },
            { text: "0", value: "0", parentVal: "170" },
            { text: "0", value: "0", parentVal: "171" },
            { text: "0", value: "0", parentVal: "172" },
            { text: "0", value: "0", parentVal: "173" },
            { text: "0", value: "0", parentVal: "174" },
            { text: "0", value: "0", parentVal: "175" },
            { text: "0", value: "0", parentVal: "176" },
            { text: "0", value: "0", parentVal: "177" },
            { text: "0", value: "0", parentVal: "178" },
            { text: "0", value: "0", parentVal: "179" },
            { text: "0", value: "0", parentVal: "180" },
            { text: "0", value: "0", parentVal: "181" },
            { text: "0", value: "0", parentVal: "182" },
            { text: "0", value: "0", parentVal: "183" },
            { text: "0", value: "0", parentVal: "184" },
            { text: "0", value: "0", parentVal: "185" },
            { text: "0", value: "0", parentVal: "186" },
            { text: "0", value: "0", parentVal: "187" },
            { text: "0", value: "0", parentVal: "188" },
            { text: "0", value: "0", parentVal: "189" },
            { text: "0", value: "0", parentVal: "190" },
            { text: "0", value: "0", parentVal: "191" },
            { text: "0", value: "0", parentVal: "192" },
            { text: "0", value: "0", parentVal: "193" },
            { text: "0", value: "0", parentVal: "194" },
            { text: "0", value: "0", parentVal: "195" },
            { text: "0", value: "0", parentVal: "196" },
            { text: "0", value: "0", parentVal: "197" },
            { text: "0", value: "0", parentVal: "198" },
            { text: "0", value: "0", parentVal: "199" },
            { text: "0", value: "0", parentVal: "200" },
            { text: "0", value: "0", parentVal: "201" },
            { text: "0", value: "0", parentVal: "202" },
            { text: "0", value: "0", parentVal: "203" },
            { text: "0", value: "0", parentVal: "204" },
            { text: "0", value: "0", parentVal: "205" },
            { text: "0", value: "0", parentVal: "206" },
            { text: "0", value: "0", parentVal: "207" },
            { text: "0", value: "0", parentVal: "208" },
            { text: "0", value: "0", parentVal: "209" },
            { text: "0", value: "0", parentVal: "210" },
            { text: "0", value: "0", parentVal: "211" },
            { text: "0", value: "0", parentVal: "212" },
            { text: "0", value: "0", parentVal: "213" },
            { text: "0", value: "0", parentVal: "214" },
            { text: "0", value: "0", parentVal: "215" },
            { text: "0", value: "0", parentVal: "216" },
            { text: "0", value: "0", parentVal: "217" },
            { text: "0", value: "0", parentVal: "218" },
            { text: "0", value: "0", parentVal: "219" },
            { text: "0", value: "0", parentVal: "220" },
            { text: "0", value: "0", parentVal: "221" },
            { text: "0", value: "0", parentVal: "222" },
            { text: "0", value: "0", parentVal: "223" },
            { text: "0", value: "0", parentVal: "224" },
            { text: "0", value: "0", parentVal: "225" },
            { text: "0", value: "0", parentVal: "226" },
            { text: "0", value: "0", parentVal: "227" },
            { text: "0", value: "0", parentVal: "228" },
            { text: "0", value: "0", parentVal: "229" },
            { text: "0", value: "0", parentVal: "230" },
            { text: "0", value: "0", parentVal: "231" },
            { text: "0", value: "0", parentVal: "232" },
            { text: "0", value: "0", parentVal: "233" },
            { text: "0", value: "0", parentVal: "234" },
            { text: "0", value: "0", parentVal: "235" },
            { text: "0", value: "0", parentVal: "236" },
            { text: "0", value: "0", parentVal: "237" },
            { text: "0", value: "0", parentVal: "238" },
            { text: "0", value: "0", parentVal: "239" },
            { text: "0", value: "0", parentVal: "240" },
            { text: "0", value: "0", parentVal: "241" },
            { text: "0", value: "0", parentVal: "242" },
            { text: "0", value: "0", parentVal: "243" }*/
        ]
      }
    ];
  }
}
